[theme]
# Medical blue as primary color
primaryColor = "#0077B6"

# Clean white background
backgroundColor = "#FFFFFF"

# Light blue tint for secondary elements
secondaryBackgroundColor = "#E6F3F8"

# Dark blue for text
textColor = "#1A374D"

# Modern, clean font
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showAnimation = false
toolbarMode = "minimal"

[runner]
fastRerenderOnChanges = true

[ui]
hideTopBar = true
animation = false
transitionDuration = 0 